name: Node.js CI

on:
  pull_request:
    branches:
    - main
    - develop

jobs:
  build-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build project
      run: yarn build
